{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Pizza_Sales\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.905.0 (24.05)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "ca32157b-6b49-434f-96a8-0a8a2cc3bbce",
        "fromColumn": "order_date",
        "fromTable": "Pizza_Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e630e9dd-3f67-40ca-a6d2-6fb19b3b9412"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Pizza_Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "order_details_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78963dc0-ca51-4e3a-9a3d-45f27b95c737",
            "sourceColumn": "order_details_id",
            "summarizeBy": "sum"
          },
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59b9a7f8-edb9-485a-9444-053582cca794",
            "sourceColumn": "order_id",
            "summarizeBy": "sum"
          },
          {
            "name": "pizza_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9fc10c5-38a2-4e65-a7e3-a508948176a5",
            "sourceColumn": "pizza_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83c69184-26d4-44c3-9e3c-18fa6bcc22f1",
            "sourceColumn": "quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "order_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "10a89921-8f66-4d12-a441-edad75868de1",
            "sourceColumn": "order_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e630e9dd-3f67-40ca-a6d2-6fb19b3b9412"
                },
                "isDefault": true,
                "relationship": "ca32157b-6b49-434f-96a8-0a8a2cc3bbce"
              }
            ]
          },
          {
            "name": "order_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "h:nn",
            "lineageTag": "a1a27c26-78df-4ea5-a3ff-63f97f3a3d42",
            "sourceColumn": "order_time",
            "summarizeBy": "none"
          },
          {
            "name": "unit_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "01f886c9-c786-46db-b51c-1d50bfbd10cb",
            "sourceColumn": "unit_price",
            "summarizeBy": "sum"
          },
          {
            "name": "total_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c7f3527b-9906-4e58-958d-9144972a9aa9",
            "sourceColumn": "total_price",
            "summarizeBy": "sum"
          },
          {
            "name": "pizza_size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9614df47-8ade-4436-9470-48a6d092132b",
            "sourceColumn": "pizza_size",
            "summarizeBy": "none"
          },
          {
            "name": "pizza_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "549de77d-225f-4547-bdcf-900c39f7a16d",
            "sourceColumn": "pizza_category",
            "summarizeBy": "none"
          },
          {
            "name": "pizza_ingredients",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45920e47-663c-4d9c-a157-4ab3d2f0f4df",
            "sourceColumn": "pizza_ingredients",
            "summarizeBy": "none"
          },
          {
            "name": "pizza_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62313d7c-faad-4560-8006-92075c7a167d",
            "sourceColumn": "pizza_name",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa462995-d32d-45d0-aa1b-40a0975e7d38",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Order Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "upper(left(Pizza_Sales[Day Name], 3))",
            "isDataTypeInferred": true,
            "lineageTag": "9d6f33a1-3277-40a9-ab5e-1833afe7d6b5",
            "sortByColumn": "Day Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c65e1ae8-2933-44d9-8ed4-549948c1eddf",
            "sourceColumn": "Day Number",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cb0d4a2-e11d-4a19-acbd-13f9ed0176e2",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9032cc2a-0871-4805-a2ac-191424e746b6",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "upper(left(Pizza_Sales[Month Name], 3)) ",
            "isDataTypeInferred": true,
            "lineageTag": "ac9cb2ac-85bc-4cd7-819d-8b66894e13eb",
            "sortByColumn": "Month Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Order Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "12f9e13d-65d0-499d-977e-b623530e7eba",
            "sourceColumn": "Order Hour",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "38e469b7-a08b-4312-92c8-65ccde80ea5d",
        "measures": [
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(Pizza_Sales[total_price]) ",
            "lineageTag": "f612ce88-794f-4d2a-b4b6-6886a7165a68"
          },
          {
            "name": "Total Orders",
            "expression": "DISTINCTCOUNT(Pizza_Sales[order_id])",
            "formatString": "#,0",
            "lineageTag": "b785a102-b0b4-4cc3-810c-5a907d38d86c"
          },
          {
            "name": "Avg Order Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Revenue]/[Total Orders] ",
            "lineageTag": "4bfb14e4-b823-4569-9361-ea1b05e28715"
          },
          {
            "name": "Total Pizzas Sold",
            "expression": "sum(Pizza_Sales[quantity]) ",
            "formatString": "#,0",
            "lineageTag": "16bc0413-604e-4508-8b27-25ab1b522d14"
          },
          {
            "name": "Avg Pizzas per Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Pizzas Sold]/[Total Orders]",
            "lineageTag": "c4e58670-1296-4754-9d39-69779e2ba07e"
          }
        ],
        "partitions": [
          {
            "name": "Pizza_Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"DESKTOP-BRAU7L5\", \"Kaggle_Pizza DB\"),",
                "    dbo_Pizza_Sales = Source{[Schema=\"dbo\",Item=\"Pizza_Sales\"]}[Data],",
                "    #\"Replaced Value M\" = Table.ReplaceValue(dbo_Pizza_Sales,\"M\",\"Medium\",Replacer.ReplaceText,{\"pizza_size\"}),",
                "    #\"Replaced Value L\" = Table.ReplaceValue(#\"Replaced Value M\",\"L\",\"Large\",Replacer.ReplaceValue,{\"pizza_size\"}),",
                "    #\"Replaced Value S\" = Table.ReplaceValue(#\"Replaced Value L\",\"S\",\"Regular\",Replacer.ReplaceValue,{\"pizza_size\"}),",
                "    #\"Replaced Value XL\" = Table.ReplaceValue(#\"Replaced Value S\",\"XL\",\"X-Large\",Replacer.ReplaceText,{\"pizza_size\"}),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Replaced Value XL\", \"Day Name\", each Date.DayOfWeekName([order_date]), type text),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Day Name\", \"Day Number\", each if [Day Name] = \"Sunday\" then 1 else if [Day Name] = \"Monday\" then 2 else if [Day Name] = \"Tuesday\" then 3 else if [Day Name] = \"Wednesday\" then 4 else if [Day Name] = \"Thursday\" then 5 else if [Day Name] = \"Friday\" then 6 else if [Day Name] = \"Saturday\" then 7 else null),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Added Conditional Column\", \"Month Name\", each Date.MonthName([order_date]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([order_date]), Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Month\",{{\"Month\", \"Month Number\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Order Hour\", each Time.Hour([order_time]), Int64.Type),",
                "    #\"Removed Errors\" = Table.AddColumn(#\"Renamed Columns\", \"Order Hour\", each Time.Hour([order_time]), Int64.Type)",
                "in",
                "    #\"Removed Errors\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_e8a9d5f0-e298-4a51-a4fd-7c658446aede",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e301de44-6e59-4a26-8379-d1bbb6fccefd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b4bb2e72-4390-4c96-996e-dc7138ee9e08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0c918851-2171-4170-ae20-66c7a6dfe5ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "91992343-613b-4cb7-8a95-37c71dd5cf4d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c3fc9744-6567-4566-9449-f6688a8f8de3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ae83ae0b-a120-4003-aa6c-f9563a8b7a21",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9364e1c3-17f5-4207-a8b4-8449d798369d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1554d051-a67f-45f2-bef0-10940126fca7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "31a3edca-4db9-4ecf-82ce-06cb634aa000",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "196614ad-8eb5-4ed0-8325-162199f0d6f1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "10ca2647-4806-4a0e-924e-6519fa86f890",
                "ordinal": 3
              }
            ],
            "lineageTag": "b9484db7-62ad-4c47-ac64-0432ee158593"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "be922e0f-5b9e-4030-9882-404b1c88e223",
        "partitions": [
          {
            "name": "DateTableTemplate_e8a9d5f0-e298-4a51-a4fd-7c658446aede",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e630e9dd-3f67-40ca-a6d2-6fb19b3b9412",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1fa950d2-4317-4017-b818-bdfc5c364a3d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1df04710-e0bc-4197-b54e-35947896d4e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "43234875-6c05-4ed4-bb05-2806ab44a5e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "79a2b42d-5f44-4626-a8ec-26ee0a6b41ca",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7b919217-049b-4f7c-82bf-bf6469237b5c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "009521a4-ff5e-4460-8de0-f259e3b9586a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "09260661-98e9-4463-995e-faa0f0dc482c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "24dbf8fc-acf4-484a-9036-1418540ec105",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8bd16b12-650e-428e-8c4b-3561b5fde4f0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "aae1ea86-2df8-4a4e-b17e-ec502a36de3e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "24dab1e5-9f14-4043-ac9b-83d9ba334022",
                "ordinal": 3
              }
            ],
            "lineageTag": "2de06f9d-77b3-49e6-8e1e-d8c9cb668e30"
          }
        ],
        "isHidden": true,
        "lineageTag": "afbfa57d-57a6-47f0-820a-19b386ae9241",
        "partitions": [
          {
            "name": "LocalDateTable_e630e9dd-3f67-40ca-a6d2-6fb19b3b9412",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Pizza_Sales'[order_date])), 1, 1), Date(Year(MAX('Pizza_Sales'[order_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}