{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"car_data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.905.0 (24.05)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "29692445-bac2-4a50-ade5-0b4210146d89",
        "fromColumn": "Date",
        "fromTable": "Calendar Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c507dce2-a5dd-42e0-9884-36400e270ed5"
      },
      {
        "name": "46ddd818-59da-4ab6-b42d-ab5e5c6b70a0",
        "fromColumn": "Date",
        "fromTable": "car_data",
        "toColumn": "Date",
        "toTable": "Calendar Table"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "car_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Car_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ab7f5f9-acc9-4930-9445-a36f2c2d71b6",
            "sourceColumn": "Car_id",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "42aa0849-b391-433d-99e1-2d6701269516",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cc82171-fb0c-402f-a078-da666d38bad8",
            "sourceColumn": "Customer_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5feae379-98e8-43e2-a8a4-bed7e2b3e980",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Annual_Income",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c89e4601-c039-44a7-9037-e3b8615337fe",
            "sourceColumn": "Annual_Income",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75bdc252-d934-4a91-9fbd-13b120ef4982",
            "sourceColumn": "Dealer_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3cf438c-c18b-4656-8b97-81705f5dfa3e",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56c71317-8f52-4f75-83af-b083932d9adb",
            "sourceColumn": "Model",
            "summarizeBy": "none"
          },
          {
            "name": "Engine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "266a0834-8c89-4474-9193-4df882662111",
            "sourceColumn": "Engine",
            "summarizeBy": "none"
          },
          {
            "name": "Transmission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69787285-b8fa-462e-aaf3-038ee26b2b0e",
            "sourceColumn": "Transmission",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58ff42df-d0d1-42a4-a240-098ee7be42d1",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e39b7270-c5a0-416f-8246-3358f277fcfb",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer_No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d38c3da-a85d-4121-be7d-d032dccb8bd2",
            "sourceColumn": "Dealer_No",
            "summarizeBy": "none"
          },
          {
            "name": "Body_Style",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b0169f7-0792-4675-97e0-0822ff942d8b",
            "sourceColumn": "Body_Style",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cabe8c80-3647-4591-a0e7-980ed22abb82",
            "sourceColumn": "Phone",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer_Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a803039-bd25-49d6-8d67-b737febe6ca0",
            "sourceColumn": "Dealer_Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90d0d11a-dc47-4407-a4c2-8de08b5a4303",
        "measures": [
          {
            "name": "YTD Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "TOTALYTD(sum(car_data[Price]), 'Calendar Table'[Date])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "4854250e-eef9-481a-8dda-b9d3c4d6cd3c"
          },
          {
            "name": "PYTD Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "CALCULATE(sum(car_data[Price]), SAMEPERIODLASTYEAR('Calendar Table'[Date]))",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "21db37ea-db70-4049-a007-cbbfcf5fa016"
          },
          {
            "name": "Sales Difference",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "[YTD Total Sales] - [PYTD Total Sales]",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "47c1c891-8438-446c-a6b3-89ced3dc7c91"
          },
          {
            "name": "Sales Diff Color",
            "expression": "if([Sales Difference] > 0, \"green\", \"red\" )",
            "lineageTag": "01c33fdc-b622-4de1-8c08-c73094b89f48"
          },
          {
            "name": "YoY Sales Growth",
            "expression": "[Sales Difference] / [PYTD Total Sales]",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "111580bb-9db3-409d-a97c-7959037b0c3c"
          },
          {
            "name": "MTD Total Sales",
            "expression": "TOTALMTD(sum(car_data[Price]), 'Calendar Table'[Date])",
            "formatString": "0",
            "lineageTag": "46c930de-eaca-409b-97c2-a6c22e254abd"
          },
          {
            "name": "MTD Total Sales KPI",
            "expression": "CONCATENATE(\"MTD Total Sales : \", Format([MTD Total Sales] / 1000000, \"$0.00M\" ))",
            "lineageTag": "03f47a69-3835-4f25-9407-8b40ea478dab"
          },
          {
            "name": "Avg Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(car_data[Price]) / count(car_data[Car_id])",
            "lineageTag": "75757de2-89cb-4f40-bab3-5bbb8ccb3f51"
          },
          {
            "name": "YTD Avg Price",
            "expression": "TOTALYTD([Avg Price], 'Calendar Table'[Date]) ",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "04dbf16a-bbd9-4ea5-ab76-bb8970e51bb6"
          },
          {
            "name": "PYTD Avg Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Avg Price], SAMEPERIODLASTYEAR('Calendar Table'[Date]))",
            "lineageTag": "d9335b42-b4d1-443f-90a7-d6f358f277fb"
          },
          {
            "name": "Avg Price Difference",
            "expression": "[YTD Avg Price] - [PYTD Avg Price]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8ef29014-1aff-4af8-a635-6a662b16c373"
          },
          {
            "name": "Avg Price Diff Color",
            "expression": "if([Avg Price Difference] > 0, \"green\", \"red\" )",
            "lineageTag": "a9c9c924-dc48-487e-aa8d-a34a58ad57d6"
          },
          {
            "name": "YoY Avg Price Growth",
            "expression": "[Avg Price Difference] / [PYTD Avg Price]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d823fd89-cc9f-41e2-9b79-618295aafb59"
          },
          {
            "name": "MTD Avg Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "TOTALMTD([Avg Price], 'Calendar Table'[Date]) ",
            "lineageTag": "28e1b403-d7d9-4fd5-a488-a5cf548e726c"
          },
          {
            "name": "MTD Avg Price KPI",
            "expression": "CONCATENATE(\"MTD Avg Price : \", Format([MTD Avg Price] / 1000, \"$0.00K\" ))",
            "lineageTag": "196ded83-983b-4575-927d-77983200cefa"
          },
          {
            "name": "YTD Cars Sold",
            "expression": "TOTALYTD(count(car_data[Car_id]), 'Calendar Table'[Date])  ",
            "formatString": "0.0",
            "lineageTag": "bb87f628-68a1-4b6f-a235-56d62379aae9"
          },
          {
            "name": "PYTD Cars Sold",
            "expression": "CALCULATE(count(car_data[Car_id]), SAMEPERIODLASTYEAR('Calendar Table'[Date]))",
            "formatString": "0",
            "lineageTag": "bba6635a-97cf-494f-88a0-05540a80846f"
          },
          {
            "name": "Cars Sold Difference",
            "expression": "[YTD Cars Sold] - [PYTD Cars Sold]",
            "formatString": "0.00",
            "lineageTag": "3d1431e8-2c68-448c-889e-e3a98e70e9ef"
          },
          {
            "name": "Cars Sold Diff Color",
            "expression": "if([Cars Sold Difference] > 0, \"green\", \"red\" )",
            "lineageTag": "153c3507-c2dc-4b45-9e7a-5f2563613051"
          },
          {
            "name": "YoY Cars Sold Growth",
            "expression": "[Cars Sold Difference] / [PYTD Cars Sold]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cb98978b-2694-48af-ab18-dfe975c37951"
          },
          {
            "name": "MTD Cars Sold",
            "expression": "TOTALMTD(count(car_data[Price]), 'Calendar Table'[Date])",
            "formatString": "0",
            "lineageTag": "fd5efe8f-972e-4852-9769-cc215930b80e"
          },
          {
            "name": "MTD Cars Sold KPI",
            "expression": "CONCATENATE(\"MTD Cars Sold : \", Format([MTD Cars Sold] / 1000, \"0.00K\" ))",
            "lineageTag": "cc9c4140-7cc7-4aef-ba2b-25620591dd78"
          },
          {
            "name": "Total Sales",
            "expression": "sum(car_data[Price])",
            "formatString": "0",
            "lineageTag": "1244156c-65ec-4d29-9d6e-a891d08504ab"
          },
          {
            "name": "Max Point on Area Chart",
            "expression": "if(MAXX(ALLSELECTED('Calendar Table'[Week]), [Total Sales]) = [Total Sales], MAXX(ALLSELECTED('Calendar Table'[Week]), [Total Sales]), blank())",
            "formatString": "0",
            "lineageTag": "494d832f-de00-46a5-902f-45beb7a37525"
          }
        ],
        "partitions": [
          {
            "name": "car_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"DESKTOP-BRAU7L5\", \"Kaggle_CarSales DB\"),",
                "    dbo_car_data = Source{[Schema=\"dbo\",Item=\"car_data\"]}[Data],",
                "    #\"Edited typo\" = Table.ReplaceValue(dbo_car_data,\"DoubleA?Overhead Camshaft\",\"Double Overhead Camshaft\",Replacer.ReplaceText,{\"Engine\"})",
                "in",
                "    #\"Edited typo\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_b542eb93-361b-4f87-a17b-a17312939841",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f8c00d62-f13a-4613-841e-de07a5fa2876",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3b635d8b-d006-43f5-b063-385680558dc1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "86b6644f-2da9-498b-adcd-b1631931f098",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cd94c3e3-9814-43dd-8f11-7c4e5ff0c75c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "156b88a0-fac3-402c-83c0-f39b05397f91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a42b4365-0861-4915-9531-16b6776e07b4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "e6fba288-1ad3-4459-8fe9-88262e3fc43a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "68c78b7e-5fd4-4cc0-8b4f-11777de2586e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cc70ca71-6cc5-4a1b-9eec-6389d8b2bcb9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ba7d2a3d-2431-427b-ac86-cebe6b02de8c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0ee742b4-c3f4-45f1-8e48-b051fb50cdee",
                "ordinal": 3
              }
            ],
            "lineageTag": "b1a29cb5-e602-4b22-861e-7b5e0f6e7933"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "58aecaef-912e-4535-b274-b4ea29d17e21",
        "partitions": [
          {
            "name": "DateTableTemplate_b542eb93-361b-4f87-a17b-a17312939841",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendar Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "75ed480208244b229c80623441710de2"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6625a703-0828-4c67-acc6-b32dd8c179fe",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c507dce2-a5dd-42e0-9884-36400e270ed5"
                },
                "isDefault": true,
                "relationship": "29692445-bac2-4a50-ade5-0b4210146d89"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "year('Calendar Table'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d34c649e-d1df-43f6-8932-e76dcdf7a542",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "format('Calendar Table'[Date], \"MMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "dee4b042-fea2-4ee8-8d34-f2a3d1e12fc4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM('Calendar Table'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a5935342-af59-4827-9d04-5c0e4be78501",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "QUARTER('Calendar Table'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "89c9663d-8d91-4bb7-8f87-785936aa75c8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "4350af67-ab67-4373-ab20-454e8bfeff93",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "afbb5017-4eec-4ccb-98ff-948e69d41e6e",
        "partitions": [
          {
            "name": "Calendar Table",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(min(car_data[Date]), max(car_data[Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c507dce2-a5dd-42e0-9884-36400e270ed5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "049d618e-7145-4d07-ae80-50d25248bd37",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2540c666-3982-4f02-a3de-065f0423e5e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8f1f2136-867c-434e-8f34-e868029ebaf3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bdd41d45-fe01-4775-ad2e-b5018f69109d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "4ab9ff7d-49b7-4bbc-a831-7e0a1f6d3883",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8c4b0d77-fee0-4385-a700-7447e901077a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "31397a21-9d01-4ce7-9f60-992275d24b58",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4e682b15-6eaf-4ebe-9f60-72228b416bce",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "38db2c01-4acd-4e94-be7f-857750aa3178",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "34865229-cd2b-4c84-8283-0b13d8a65ba4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2ba7d7c1-3d15-461d-b9a7-9c9ca8af8656",
                "ordinal": 3
              }
            ],
            "lineageTag": "d207b6df-55d9-4aa3-ad7b-e67795f10031"
          }
        ],
        "isHidden": true,
        "lineageTag": "aeaeb7db-da9a-40fa-96aa-4513ebfe9098",
        "partitions": [
          {
            "name": "LocalDateTable_c507dce2-a5dd-42e0-9884-36400e270ed5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Table'[Date])), 1, 1), Date(Year(MAX('Calendar Table'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}